import streamlit as st
import pandas as pd

# Initialize all session state variables at the top of your main app
if 'synthetic_data' not in st.session_state:
    st.session_state['synthetic_data'] = pd.DataFrame()

if 'simulation_log' not in st.session_state:
    # Initialize with expected columns to avoid KeyError
    st.session_state['simulation_log'] = pd.DataFrame(columns=[
        'Scenario ID', 'Timestamp', 'Action', 'Impact', 'Risk_Level', 
        # Add other expected columns based on your application
    ])

# Add other potential session state variables
if 'risk_appetite_thresholds' not in st.session_state:
    st.session_state['risk_appetite_thresholds'] = {}

if 'simulation_results' not in st.session_state:
    st.session_state['simulation_results'] = pd.DataFrame()

st.set_page_config(page_title="QuLab: Risk Apetite & Governance Simulator", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: Risk Apetite & Governance Simulator")
st.divider()

st.markdown("""
This application simulates risk management strategies within a firm's risk appetite.
It allows users to generate synthetic risk scenarios, define risk appetite thresholds,
simulate risk management actions, and visualize the impact of these actions.
""")

page = st.sidebar.selectbox(
    label="Navigation",
    options=["Data Generation & Risk Appetite", "Scenario Simulation", "Impact Analysis"]
)

if page == "Data Generation & Risk Appetite":
    from application_pages.page1 import run_page1
    run_page1()
elif page == "Scenario Simulation":
    from application_pages.page2 import run_page2
    run_page2()
elif page == "Impact Analysis":
    from application_pages.page3 import run_page3
    run_page3()

# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
